pipeline {
  agent any
  tools {
    jdk 'JDK21'
  }
  stages {
    stage('Build') {
      steps {
        sh 'mvn clean package'
      }
    }
    stage('Test') {
      steps {
        sh 'mvn test'
      }
    }
    stage('Docker') {
      steps {
          sh '''
            echo "Current directory:"
            pwd
            echo "Content of current directory:"
            ls -la
            docker build -t service-spreadsheet:latest -f microservice/spreadsheet
          '''
        }
    }
  }
}