pipeline {
  agent any
  tools {
    jdk 'JDK21'
  }
  stages {
    stage('Build') {
      steps {
        sh 'mvn clean package'
      }
    }
    stage('Test') {
      steps {
        sh 'mvn test'
      }
    }
    stage('Docker') {
      steps {
        dir('microservice/spreadsheet') {
            sh 'docker build -t service-spreadsheet:latest .'
        }
      }
    }
  }
}